### ISSUE TITLE
invalid mode error

### ISSUE THREAD

**Issue by chiewoo** [gwpy/gwsumm#29] opened 2015-10-30 02:03 UTC
I tested this summary page following the Wiki's instruction page. I just type the command:
gw_summary --nds --verbose --ifo L1 --output-dir /home/${USER}/public_html/detchar --verbose --config-file ${RUN_DIR}/defaults.ini --config-file ${RUN_DUR}/ihope.ini --max-processes 40 --day 20140222
usage: gw_summary [-h] [-V] {week,gps,day,month} ...
gw_summary: error: argument mode: invalid choice: 'L1' (choose from 'week', 'gps', 'day', 'month')

and get an error message, showing L1 ifo option. But I don't see what's going on here.

**Comment by duncanmmacleod** [comment] 2015-10-30 21:54
This is a duplicate of #30.

**Closed by duncanmmacleod** 2015-10-30 21:54 UTC
